---

variables:
  CI_PYTHON_UNIVERSAL: "yes"

include:
  - project: 'dpres/gitlab-ci-pipeline'
    ref: KDKPAS-2577
    file:
      - '/pipeline/common.yml'
      - '/pipeline/fddps.yml'
      - '/pipeline/kppas.yml'
      - '/pipeline/sapa.yml'
